### ISSUE TITLE
use the new pkg/pip_install_requirements for all steps

### ISSUE THREAD

**Issue by kalikaneko** [parmegv/buildbot-bitmask#11]
right now soledad builder uses still the setup develop method

**Comment by parmegv** [comment]
you already did it, right?

https://github.com/parmegv/buildbot-bitmask/blob/91bf1deb9b9c137f2625367862b483000a354d4d/master.cfg#L89

**Comment by kalikaneko** [comment]
true, I hadn't looked at the soledad lines, they're too long :P 
yeah, we can close
