### ISSUE TITLE
add a builder that builds and upload sumo tarballs on each bitmask build

### ISSUE THREAD

**Issue by kalikaneko** [parmegv/buildbot-bitmask#19]
"make sumo tarball"
this can  be a separate builder or a final step in the bitmask_client tests (for only one slave, that is, the one running in our machine --- see how to config this)

**Comment by parmegv** [comment]
Merged: https://github.com/parmegv/buildbot-bitmask/commit/dc5e64379e4247fd2d943a247fabca6524af17c2
