### ISSUE TITLE
setup.sh script doesn't install buildbot 

### ISSUE THREAD

**Issue by kalikaneko** [parmegv/buildbot-bitmask#2]
error is something like "cannot find buildbot.statistics"
script should be changed to setup.py install buildbot master from within the sandbox venv

**Comment by kalikaneko** [comment]
now that I remember, the way I got it working was installing the "master" in develop mode inside the sandbox

**Comment by parmegv** [comment]
setup.sh doesn't install buildbot at all, it just assumes it is installed.

What I did in my server was to checkout the master branch of buildbot somewhere, activate the sandbox, and then move to buildbot-bitmask folder and do whatever.

**Comment by kalikaneko** [comment]
ah, that's true. I started fiddling assuming stuff.
we either should document it (why is it that we want/need 9.0?) it's quite cool anyway...
or create a little bootstrap script.

the current setup script is flawed for our case: it creates the virtualenv, and expects buildbot to be installed right away?

**Comment by parmegv** [comment]
We need 0.9.0 because it has a better github hook (which detects pull requests).

The viritualenv is created just to run buildbot, not to install it, I don't get your point. Why is that flawed?

**Comment by kalikaneko** [comment]
with "virtualenv --python..." you are creating the virtualenv if it doesn't exist.
then you run "buildbot create..." but this is not yet installed in the venv.

**Comment by parmegv** [comment]
Fixed in https://github.com/parmegv/buildbot-bitmask/commit/0da8eb66b51424fc8fa0a49a2612bbda7228f00b
