### ISSUE TITLE
ignore files, add exceptions on pep8

### ISSUE THREAD

**Issue by kalikaneko** [parmegv/buildbot-bitmask#23]
http://noise.rhizolab.org:8010/#/builders/3/builds/41/steps/5/logs/stdio

we should ignore some files: setup.py, versioneer, src._version
also, we could ignore the "line-too-long" warning

**Comment by parmegv** [comment]
Fixed in https://github.com/parmegv/buildbot-bitmask/commit/1adf4c63d343aae5ef1d4e152f6c9017a370e55c
