### ISSUE TITLE
document base dependencies somewhere

### ISSUE THREAD

**Issue by kalikaneko** [parmegv/buildbot-bitmask#6]
Since we're going to be hitting lots of building bugs, we should gather them alltogether somewhere so that we can review the building docs.
One of the libs, for instance, is libffi
'''
403No package 'libffi' found
404compiling '_configtest.c':
405__thread int some_threadlocal_variable_42;
406
407x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -c _configtest.c -o _configtest.o
408success!
409removing: _configtest.c _configtest.o
410c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
411 #include 
412                 ^
'''

**Comment by kalikaneko** [comment]
well, we have a little README in there... let's check deps against https://leap.se/en/docs/client/dev-environment.
I don't think it's bad to have the snippet handy in here too

**Comment by parmegv** [comment]
Updating leap.se website with make, libzmq-dev and protobuf-compiler: https://github.com/leapcode/leap_se/pull/5

**Comment by parmegv** [comment]
Merged leap.se update https://github.com/leapcode/leap_se/commit/6ac3213a36952c57a7cca23b9d598f6a3bb4d2fa
Merged https://github.com/parmegv/buildbot-bitmask/commit/4cfc07a01538e328ba324f98eef78849147ead30
