### ISSUE TITLE
add upgrade steps

### ISSUE THREAD

**Issue by kalikaneko** [parmegv/buildbot-bitmask#7]
in order to work, in wheezy at least, you need to:
- pip install -U pip
- pip install -U distribute
- pip install -U setuptools

... and right then the prebuilt_frontend stuff will work. otherwise you'll get an error saying that buildbot-www is not found ;)

**Comment by kalikaneko** [comment]
this is needed in two places:
- as documentation for setting up the master
- as an extra pre-step for the builders. see for instance this common builder fail:

```
23Downloading/unpacking mock (from -r pkg/requirements-testing.pip (line 1))
24  Running setup.py egg_info for package mock
25    mock requires setuptools>=17.1. Aborting installation
26    Complete output from command python setup.py egg_info:
27    mock requires setuptools>=17.1. Aborting installation
```

**Comment by parmegv** [comment]
What if we specified the needed version of those dependencies somewhere?

It seems more natural to me to use the pip files for this, instead of adding commands to the buildbot configuration, but I'm open to discussion of course :)

**Comment by parmegv** [comment]
Mmm, I tried to specify the setuptools version in requirements-testing.pip but it didn't work:

Downloading/unpacking distribute from https://pypi.python.org/packages/source/d/distribute/distribute-0.7.3.zip#md5=c6c59594a7b180af57af8a0cc0cf5b4a (from -r pkg/requirements-testing.pip (line 1))
24  Running setup.py egg_info for package distribute
25  
26Downloading/unpacking mock (from -r pkg/requirements-testing.pip (line 2))
27  Running setup.py egg_info for package mock
28    mock requires setuptools>=17.1. Aborting installation
29    Complete output from command python setup.py egg_info:
30    mock requires setuptools>=17.1. Aborting installation

**Comment by parmegv** [comment]
@kalikaneko , tell me if that seems ok to you.

**Comment by kalikaneko** [comment]
parmegv: if you want the long way, it could be a script that:
- check current version of {pip,setuptools,distribute}
- compares to whatever version gives the problem (we don't know)
- upgrades

if given to choose between (a) spending time in this script, (b) having it running for every leap env setup everywhere or (c) adding a step on the factories, specifying that if buildbot is not wheezy can be removed, I think the quick solution is (c)

Also, pinning the dependencies is a bad idea generally. it messes up with packaging a lot.

**Comment by kalikaneko** [comment]
(a) and (b) are actually the same thing :P
